# Generated by Django 5.2.6 on 2025-09-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0003_rename_order_orderitem_user_and_more'),
    ]

    operations = [
        # Rename title to name in MenuItem
        migrations.RenameField(
            model_name='menuitem',
            old_name='title',
            new_name='name',
        ),
        # Add description field
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        # Add image field
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
        # Create Booking model
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('number_of_guests', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
